[phases.setup]
nixPkgs = ["chromium", "nss", "nspr", "atk", "gtk3", "gdk-pixbuf", "glib", "pango", "cairo", "freetype", "fontconfig", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libXtst", "xorg.libXi", "xorg.libXdamage", "xorg.libXcomposite", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb", "libxkbcommon", "libdrm", "mesa", "libGL", "alsa-lib", "dbus", "cups", "expat", "zlib", "libpng", "libjpeg", "libtiff", "libwebp", "wget", "gnupg"]

[phases.install]
cmds = [
  "apt-get update && apt-get install -y wget gnupg software-properties-common unzip",
  "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
  "apt-get update && apt-get install -y google-chrome-stable",
  "wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip",
  "unzip /tmp/chromedriver.zip -d /usr/bin/",
  "chmod +x /usr/bin/chromedriver",
  "google-chrome --version",
  "chromedriver --version"
]

[phases.build]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "python run_bot.py"